language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t alexlapushinski/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alexlapushinski/docker-react npm run test
